VERSION="2.2.1"

ACCOUNTS=["GCB3YBBRVESW2FO4HPKUHP77WRKOKQ7ZCUFVSOKGDHAHZSEJCMBR5P3Y"]

[DOCUMENTATION]
ORG_NAME="Grayscale"
ORG_URL="https://www.grayscale-stellar.com/"
ORG_DESCRIPTION="Grayscale is the worldâ€™s leading crypto asset manager by assets under management. We transform disruptive technologies of the future into investment opportunities today."
ORG_LOGO="https://www.grayscale-stellar.com/gscale.jpg"


[[CURRENCIES]]
code="GBAT"
status="live"
display_decimals=5
issuer="GCB3YBBRVESW2FO4HPKUHP77WRKOKQ7ZCUFVSOKGDHAHZSEJCMBR5P3Y"
anchor_asset_type="crypto"
name="Grayscale Basic"
desc="Grayscale Basic Attention Token Trust is one of the first securities solely and passively invested in the Basic Attention Token"
image="https://www.grayscale-stellar.com/gscale.jpg"
